//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adion.FA.Infrastructure.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adion.FA.Infrastructure.I18n.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Progressiveness.
        /// </summary>
        public static string ActivateProgressiveness {
            get {
                return ResourceManager.GetString("ActivateProgressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        public static string Adjust {
            get {
                return ResourceManager.GetString("Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Average.
        /// </summary>
        public static string AdjustByAverage {
            get {
                return ResourceManager.GetString("AdjustByAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Config.
        /// </summary>
        public static string AdvancedConfig {
            get {
                return ResourceManager.GetString("AdvancedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string America {
            get {
                return ResourceManager.GetString("America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string America1 {
            get {
                return ResourceManager.GetString("America1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Later.
        /// </summary>
        public static string AndLater {
            get {
                return ResourceManager.GetString("AndLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Automat.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        public static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        public static string Asia1 {
            get {
                return ResourceManager.GetString("Asia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembled.
        /// </summary>
        public static string Assembled {
            get {
                return ResourceManager.GetString("Assembled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembled Builder.
        /// </summary>
        public static string AssembledBuilder {
            get {
                return ResourceManager.GetString("AssembledBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembled Builder Information.
        /// </summary>
        public static string AssembledBuilderInformation {
            get {
                return ResourceManager.GetString("AssembledBuilderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Iterations.
        /// </summary>
        public static string AssemblyIterations {
            get {
                return ResourceManager.GetString("AssemblyIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Percent.
        /// </summary>
        public static string AssemblyPercent {
            get {
                return ResourceManager.GetString("AssemblyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous Mode.
        /// </summary>
        public static string AsynchronousMode {
            get {
                return ResourceManager.GetString("AsynchronousMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async Mode.
        /// </summary>
        public static string AsyncMode {
            get {
                return ResourceManager.GetString("AsyncMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Config.
        /// </summary>
        public static string AutoAdjustConfig {
            get {
                return ResourceManager.GetString("AutoAdjustConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Price.
        /// </summary>
        public static string ClosePrice {
            get {
                return ResourceManager.GetString("ClosePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse / Expand Tree.
        /// </summary>
        public static string CollapseExpandTree {
            get {
                return ResourceManager.GetString("CollapseExpandTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name.
        /// </summary>
        public static string ConfigurationName {
            get {
                return ResourceManager.GetString("ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Settings.
        /// </summary>
        public static string ConfigurationSettings {
            get {
                return ResourceManager.GetString("ConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation.
        /// </summary>
        public static string Correlation {
            get {
                return ResourceManager.GetString("Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation Detail.
        /// </summary>
        public static string CorrelationDetail {
            get {
                return ResourceManager.GetString("CorrelationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation DOWN.
        /// </summary>
        public static string CorrelationDOWN {
            get {
                return ResourceManager.GetString("CorrelationDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation Result.
        /// </summary>
        public static string CorrelationResult {
            get {
                return ResourceManager.GetString("CorrelationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation UP.
        /// </summary>
        public static string CorrelationUP {
            get {
                return ResourceManager.GetString("CorrelationUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Strategy.
        /// </summary>
        public static string CrossStrategy {
            get {
                return ResourceManager.GetString("CrossStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Pair.
        /// </summary>
        public static string CurrencyPair {
            get {
                return ResourceManager.GetString("CurrencyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration.
        /// </summary>
        public static string CurrentConfiguration {
            get {
                return ResourceManager.GetString("CurrentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darwinex.
        /// </summary>
        public static string Darwinex {
            get {
                return ResourceManager.GetString("Darwinex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals.
        /// </summary>
        public static string Decimals {
            get {
                return ResourceManager.GetString("Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Configuration.
        /// </summary>
        public static string DefaultConfiguration {
            get {
                return ResourceManager.GetString("DefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Enviroment.
        /// </summary>
        public static string DefaultEnviroment {
            get {
                return ResourceManager.GetString("DefaultEnviroment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        public static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN Node Assembled.
        /// </summary>
        public static string DOWNNodeAssembled {
            get {
                return ResourceManager.GetString("DOWNNodeAssembled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven.
        /// </summary>
        public static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Europe1 {
            get {
                return ResourceManager.GetString("Europe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Name.
        /// </summary>
        public static string ExtractionName {
            get {
                return ResourceManager.GetString("ExtractionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractor.
        /// </summary>
        public static string Extractor {
            get {
                return ResourceManager.GetString("Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractor Information.
        /// </summary>
        public static string ExtractorInformation {
            get {
                return ResourceManager.GetString("ExtractorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteen.
        /// </summary>
        public static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex.
        /// </summary>
        public static string Forex {
            get {
                return ResourceManager.GetString("Forex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourteen.
        /// </summary>
        public static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date In Region.
        /// </summary>
        public static string FromDateInRegion {
            get {
                return ResourceManager.GetString("FromDateInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Configuration.
        /// </summary>
        public static string GlobalConfiguration {
            get {
                return ResourceManager.GetString("GlobalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        public static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Hour.
        /// </summary>
        public static string H4 {
            get {
                return ResourceManager.GetString("H4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. End.
        /// </summary>
        public static string HEnd {
            get {
                return ResourceManager.GetString("HEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. Initial.
        /// </summary>
        public static string HInitial {
            get {
                return ResourceManager.GetString("HInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Data.
        /// </summary>
        public static string HistoryData {
            get {
                return ResourceManager.GetString("HistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        public static string Instance {
            get {
                return ResourceManager.GetString("Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Details.
        /// </summary>
        public static string InstanceDetails {
            get {
                return ResourceManager.GetString("InstanceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances.
        /// </summary>
        public static string Instances {
            get {
                return ResourceManager.GetString("Instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (IS).
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Schedule.
        /// </summary>
        public static string IsSchedule {
            get {
                return ResourceManager.GetString("IsSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loser.
        /// </summary>
        public static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Minute.
        /// </summary>
        public static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minute.
        /// </summary>
        public static string M15 {
            get {
                return ResourceManager.GetString("M15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minute.
        /// </summary>
        public static string M30 {
            get {
                return ResourceManager.GetString("M30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minute.
        /// </summary>
        public static string M5 {
            get {
                return ResourceManager.GetString("M5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Data.
        /// </summary>
        public static string MarketData {
            get {
                return ResourceManager.GetString("MarketData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market History Data.
        /// </summary>
        public static string MarketHistoryData {
            get {
                return ResourceManager.GetString("MarketHistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market History Data Name.
        /// </summary>
        public static string MarketHistoryDataName {
            get {
                return ResourceManager.GetString("MarketHistoryDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Region.
        /// </summary>
        public static string MarketRegion {
            get {
                return ResourceManager.GetString("MarketRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Adjust Config.
        /// </summary>
        public static string MaxAdjustConfig {
            get {
                return ResourceManager.GetString("MaxAdjustConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Messages Required.
        /// </summary>
        public static string MaximumMessagesRequired {
            get {
                return ResourceManager.GetString("MaximumMessagesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Price.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M. End.
        /// </summary>
        public static string MEnd {
            get {
                return ResourceManager.GetString("MEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Input.
        /// </summary>
        public static string MessageInput {
            get {
                return ResourceManager.GetString("MessageInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Output.
        /// </summary>
        public static string MessageOutput {
            get {
                return ResourceManager.GetString("MessageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages from Current Period.
        /// </summary>
        public static string MessagesFromCurrentPeriod {
            get {
                return ResourceManager.GetString("MessagesFromCurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Assembly Percent.
        /// </summary>
        public static string MinAssemblyPercent {
            get {
                return ResourceManager.GetString("MinAssemblyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        public static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M. Initial.
        /// </summary>
        public static string MInitial {
            get {
                return ResourceManager.GetString("MInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes Under Test.
        /// </summary>
        public static string NodesUnderTest {
            get {
                return ResourceManager.GetString("NodesUnderTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTotals.
        /// </summary>
        public static string NTotals {
            get {
                return ResourceManager.GetString("NTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Transactions Found.
        /// </summary>
        public static string NumberOfTransactionsFound {
            get {
                return ResourceManager.GetString("NumberOfTransactionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Target Transactions.
        /// </summary>
        public static string NumberTargetTransactions {
            get {
                return ResourceManager.GetString("NumberTargetTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Test.
        /// </summary>
        public static string OffTest {
            get {
                return ResourceManager.GetString("OffTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string Older {
            get {
                return ResourceManager.GetString("Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Price.
        /// </summary>
        public static string OpenPrice {
            get {
                return ResourceManager.GetString("OpenPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string Opportunities {
            get {
                return ResourceManager.GetString("Opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (OS).
        /// </summary>
        public static string OS {
            get {
                return ResourceManager.GetString("OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path File.
        /// </summary>
        public static string PathFile {
            get {
                return ResourceManager.GetString("PathFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path File Templates.
        /// </summary>
        public static string PathFileTemplates {
            get {
                return ResourceManager.GetString("PathFileTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period In Sample (IS).
        /// </summary>
        public static string PeriodInSample {
            get {
                return ResourceManager.GetString("PeriodInSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Out Sample (OS).
        /// </summary>
        public static string PeriodOutSample {
            get {
                return ResourceManager.GetString("PeriodOutSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned.
        /// </summary>
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Type.
        /// </summary>
        public static string PositionType {
            get {
                return ResourceManager.GetString("PositionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressiveness.
        /// </summary>
        public static string Progressiveness {
            get {
                return ResourceManager.GetString("Progressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Configuration.
        /// </summary>
        public static string ProjectConfiguration {
            get {
                return ResourceManager.GetString("ProjectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Configuration Restore.
        /// </summary>
        public static string ProjectConfigurationRestore {
            get {
                return ResourceManager.GetString("ProjectConfigurationRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Global Configuration.
        /// </summary>
        public static string ProjectGlobalConfiguration {
            get {
                return ResourceManager.GetString("ProjectGlobalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        public static string ProjectInformation {
            get {
                return ResourceManager.GetString("ProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio DOWN.
        /// </summary>
        public static string RatioDOWN {
            get {
                return ResourceManager.GetString("RatioDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio Max.
        /// </summary>
        public static string RatioMax {
            get {
                return ResourceManager.GetString("RatioMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio UP.
        /// </summary>
        public static string RatioUP {
            get {
                return ResourceManager.GetString("RatioUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread.
        /// </summary>
        public static string Spread {
            get {
                return ResourceManager.GetString("Spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop On Target Found.
        /// </summary>
        public static string StopOnTargetFound {
            get {
                return ResourceManager.GetString("StopOnTargetFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Process.
        /// </summary>
        public static string StopProcess {
            get {
                return ResourceManager.GetString("StopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Builder.
        /// </summary>
        public static string StrategyBuilder {
            get {
                return ResourceManager.GetString("StrategyBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Builder Information.
        /// </summary>
        public static string StrategyBuilderInformation {
            get {
                return ResourceManager.GetString("StrategyBuilderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Tester.
        /// </summary>
        public static string StrategyTester {
            get {
                return ResourceManager.GetString("StrategyTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Rate.
        /// </summary>
        public static string SuccessRate {
            get {
                return ResourceManager.GetString("SuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Inverse Operation.
        /// </summary>
        public static string TakeInverseOperation {
            get {
                return ResourceManager.GetString("TakeInverseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target DOWN.
        /// </summary>
        public static string TargetDOWN {
            get {
                return ResourceManager.GetString("TargetDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target UP.
        /// </summary>
        public static string TargetUP {
            get {
                return ResourceManager.GetString("TargetUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporality.
        /// </summary>
        public static string Temporality {
            get {
                return ResourceManager.GetString("Temporality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test in MetaTrader.
        /// </summary>
        public static string TestInMetaTrader {
            get {
                return ResourceManager.GetString("TestInMetaTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteen.
        /// </summary>
        public static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date In Region.
        /// </summary>
        public static string ToDateInRegion {
            get {
                return ResourceManager.GetString("ToDateInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Assembly Iterations.
        /// </summary>
        public static string TotalAssemblyIterations {
            get {
                return ResourceManager.GetString("TotalAssemblyIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Days.
        /// </summary>
        public static string TotalDays {
            get {
                return ResourceManager.GetString("TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DOWN.
        /// </summary>
        public static string TotalDOWN {
            get {
                return ResourceManager.GetString("TotalDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Losers.
        /// </summary>
        public static string TotalLosers {
            get {
                return ResourceManager.GetString("TotalLosers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total UP.
        /// </summary>
        public static string TotalUP {
            get {
                return ResourceManager.GetString("TotalUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Winners.
        /// </summary>
        public static string TotalWinners {
            get {
                return ResourceManager.GetString("TotalWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader.
        /// </summary>
        public static string Trader {
            get {
                return ResourceManager.GetString("Trader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader Center.
        /// </summary>
        public static string TraderCenter {
            get {
                return ResourceManager.GetString("TraderCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Target.
        /// </summary>
        public static string TransactionsTarget {
            get {
                return ResourceManager.GetString("TransactionsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Output.
        /// </summary>
        public static string TreeOutput {
            get {
                return ResourceManager.GetString("TreeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve.
        /// </summary>
        public static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        public static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Market Data.
        /// </summary>
        public static string UploadMarketData {
            get {
                return ResourceManager.GetString("UploadMarketData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP Node Assembled.
        /// </summary>
        public static string UPNodeAssembled {
            get {
                return ResourceManager.GetString("UPNodeAssembled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation.
        /// </summary>
        public static string Variation {
            get {
                return ResourceManager.GetString("Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen.
        /// </summary>
        public static string Volumen {
            get {
                return ResourceManager.GetString("Volumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weka.
        /// </summary>
        public static string Weka {
            get {
                return ResourceManager.GetString("Weka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weka Information.
        /// </summary>
        public static string WekaInformation {
            get {
                return ResourceManager.GetString("WekaInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Financial Automat.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Nodes.
        /// </summary>
        public static string WinningNodes {
            get {
                return ResourceManager.GetString("WinningNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Strategy.
        /// </summary>
        public static string WinningStrategy {
            get {
                return ResourceManager.GetString("WinningStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Strategy DOWN.
        /// </summary>
        public static string WinningStrategyDOWN {
            get {
                return ResourceManager.GetString("WinningStrategyDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Strategy Total DOWN.
        /// </summary>
        public static string WinningStrategyTotalDOWN {
            get {
                return ResourceManager.GetString("WinningStrategyTotalDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Strategy Total UP.
        /// </summary>
        public static string WinningStrategyTotalUP {
            get {
                return ResourceManager.GetString("WinningStrategyTotalUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Strategy UP.
        /// </summary>
        public static string WinningStrategyUP {
            get {
                return ResourceManager.GetString("WinningStrategyUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning Trees.
        /// </summary>
        public static string WinningTrees {
            get {
                return ResourceManager.GetString("WinningTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Schedules.
        /// </summary>
        public static string WithoutSchedules {
            get {
                return ResourceManager.GetString("WithoutSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
