//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdionFA.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdionFA.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Builder.
        /// </summary>
        public static string AssemblyBuilder {
            get {
                return ResourceManager.GetString("AssemblyBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Builder Completed.
        /// </summary>
        public static string AssemblyBuilderCompleted {
            get {
                return ResourceManager.GetString("AssemblyBuilderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing Builder.
        /// </summary>
        public static string CrossingBuilder {
            get {
                return ResourceManager.GetString("CrossingBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossing Builder Completed.
        /// </summary>
        public static string CrossingBuilderCompleted {
            get {
                return ResourceManager.GetString("CrossingBuilderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractor.
        /// </summary>
        public static string Extractor {
            get {
                return ResourceManager.GetString("Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving.
        /// </summary>
        public static string FailEntitySave {
            get {
                return ResourceManager.GetString("FailEntitySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filepath.
        /// </summary>
        public static string Filepath {
            get {
                return ResourceManager.GetString("Filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Configuration.
        /// </summary>
        public static string GlobalConfiguration {
            get {
                return ResourceManager.GetString("GlobalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical data file is empty.
        /// </summary>
        public static string HistoricalDataEmpty {
            get {
                return ResourceManager.GetString("HistoricalDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Builder.
        /// </summary>
        public static string NodeBuilder {
            get {
                return ResourceManager.GetString("NodeBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Builder Completed.
        /// </summary>
        public static string NodeBuilderCompleted {
            get {
                return ResourceManager.GetString("NodeBuilderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is required.
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Configuration.
        /// </summary>
        public static string ProjectConfiguration {
            get {
                return ResourceManager.GetString("ProjectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Project Configuration.
        /// </summary>
        public static string RestoreProjectConfiguration {
            get {
                return ResourceManager.GetString("RestoreProjectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string SuccessEntitySave {
            get {
                return ResourceManager.GetString("SuccessEntitySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeframe.
        /// </summary>
        public static string Timeframe {
            get {
                return ResourceManager.GetString("Timeframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
