//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdionFA.Infrastructure.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CurrenciesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrenciesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdionFA.Infrastructure.I18n.Resources.CurrenciesResources", typeof(CurrenciesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF.
        /// </summary>
        public static string ADF {
            get {
                return ResourceManager.GetString("ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADP.
        /// </summary>
        public static string ADP {
            get {
                return ResourceManager.GetString("ADP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED.
        /// </summary>
        public static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFA.
        /// </summary>
        public static string AFA {
            get {
                return ResourceManager.GetString("AFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFN.
        /// </summary>
        public static string AFN {
            get {
                return ResourceManager.GetString("AFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMD.
        /// </summary>
        public static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANG.
        /// </summary>
        public static string ANG {
            get {
                return ResourceManager.GetString("ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOA.
        /// </summary>
        public static string AOA {
            get {
                return ResourceManager.GetString("AOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AON.
        /// </summary>
        public static string AON {
            get {
                return ResourceManager.GetString("AON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARS.
        /// </summary>
        public static string ARS {
            get {
                return ResourceManager.GetString("ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATS.
        /// </summary>
        public static string ATS {
            get {
                return ResourceManager.GetString("ATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUD.
        /// </summary>
        public static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWG.
        /// </summary>
        public static string AWG {
            get {
                return ResourceManager.GetString("AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZM.
        /// </summary>
        public static string AZM {
            get {
                return ResourceManager.GetString("AZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZN.
        /// </summary>
        public static string AZN {
            get {
                return ResourceManager.GetString("AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM.
        /// </summary>
        public static string BAM {
            get {
                return ResourceManager.GetString("BAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBD.
        /// </summary>
        public static string BBD {
            get {
                return ResourceManager.GetString("BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDT.
        /// </summary>
        public static string BDT {
            get {
                return ResourceManager.GetString("BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEF.
        /// </summary>
        public static string BEF {
            get {
                return ResourceManager.GetString("BEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGL.
        /// </summary>
        public static string BGL {
            get {
                return ResourceManager.GetString("BGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGN.
        /// </summary>
        public static string BGN {
            get {
                return ResourceManager.GetString("BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHD.
        /// </summary>
        public static string BHD {
            get {
                return ResourceManager.GetString("BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIF.
        /// </summary>
        public static string BIF {
            get {
                return ResourceManager.GetString("BIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMD.
        /// </summary>
        public static string BMD {
            get {
                return ResourceManager.GetString("BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BND.
        /// </summary>
        public static string BND {
            get {
                return ResourceManager.GetString("BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOB.
        /// </summary>
        public static string BOB {
            get {
                return ResourceManager.GetString("BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRL.
        /// </summary>
        public static string BRL {
            get {
                return ResourceManager.GetString("BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD.
        /// </summary>
        public static string BSD {
            get {
                return ResourceManager.GetString("BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTN.
        /// </summary>
        public static string BTN {
            get {
                return ResourceManager.GetString("BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BWP.
        /// </summary>
        public static string BWP {
            get {
                return ResourceManager.GetString("BWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYR.
        /// </summary>
        public static string BYR {
            get {
                return ResourceManager.GetString("BYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZD.
        /// </summary>
        public static string BZD {
            get {
                return ResourceManager.GetString("BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        public static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDF.
        /// </summary>
        public static string CDF {
            get {
                return ResourceManager.GetString("CDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF.
        /// </summary>
        public static string CHF {
            get {
                return ResourceManager.GetString("CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP.
        /// </summary>
        public static string CLP {
            get {
                return ResourceManager.GetString("CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNY.
        /// </summary>
        public static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COP.
        /// </summary>
        public static string COP {
            get {
                return ResourceManager.GetString("COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        public static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUC.
        /// </summary>
        public static string CUC {
            get {
                return ResourceManager.GetString("CUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUP.
        /// </summary>
        public static string CUP {
            get {
                return ResourceManager.GetString("CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVE.
        /// </summary>
        public static string CVE {
            get {
                return ResourceManager.GetString("CVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYP.
        /// </summary>
        public static string CYP {
            get {
                return ResourceManager.GetString("CYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZK.
        /// </summary>
        public static string CZK {
            get {
                return ResourceManager.GetString("CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEM.
        /// </summary>
        public static string DEM {
            get {
                return ResourceManager.GetString("DEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJF.
        /// </summary>
        public static string DJF {
            get {
                return ResourceManager.GetString("DJF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKK.
        /// </summary>
        public static string DKK {
            get {
                return ResourceManager.GetString("DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOP.
        /// </summary>
        public static string DOP {
            get {
                return ResourceManager.GetString("DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZD.
        /// </summary>
        public static string DZD {
            get {
                return ResourceManager.GetString("DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECS.
        /// </summary>
        public static string ECS {
            get {
                return ResourceManager.GetString("ECS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEK.
        /// </summary>
        public static string EEK {
            get {
                return ResourceManager.GetString("EEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGP.
        /// </summary>
        public static string EGP {
            get {
                return ResourceManager.GetString("EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP.
        /// </summary>
        public static string ESP {
            get {
                return ResourceManager.GetString("ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETB.
        /// </summary>
        public static string ETB {
            get {
                return ResourceManager.GetString("ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EURUSD {
            get {
                return ResourceManager.GetString("EURUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIM.
        /// </summary>
        public static string FIM {
            get {
                return ResourceManager.GetString("FIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FJD.
        /// </summary>
        public static string FJD {
            get {
                return ResourceManager.GetString("FJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FKP.
        /// </summary>
        public static string FKP {
            get {
                return ResourceManager.GetString("FKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRF.
        /// </summary>
        public static string FRF {
            get {
                return ResourceManager.GetString("FRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        public static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        public static string GBP1 {
            get {
                return ResourceManager.GetString("GBP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        public static string GBP2 {
            get {
                return ResourceManager.GetString("GBP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEL.
        /// </summary>
        public static string GEL {
            get {
                return ResourceManager.GetString("GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHC.
        /// </summary>
        public static string GHC {
            get {
                return ResourceManager.GetString("GHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHS.
        /// </summary>
        public static string GHS {
            get {
                return ResourceManager.GetString("GHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIP.
        /// </summary>
        public static string GIP {
            get {
                return ResourceManager.GetString("GIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMD.
        /// </summary>
        public static string GMD {
            get {
                return ResourceManager.GetString("GMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNF.
        /// </summary>
        public static string GNF {
            get {
                return ResourceManager.GetString("GNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRD.
        /// </summary>
        public static string GRD {
            get {
                return ResourceManager.GetString("GRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTQ.
        /// </summary>
        public static string GTQ {
            get {
                return ResourceManager.GetString("GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYD.
        /// </summary>
        public static string GYD {
            get {
                return ResourceManager.GetString("GYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKD.
        /// </summary>
        public static string HKD {
            get {
                return ResourceManager.GetString("HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HNL.
        /// </summary>
        public static string HNL {
            get {
                return ResourceManager.GetString("HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRK.
        /// </summary>
        public static string HRK {
            get {
                return ResourceManager.GetString("HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTG.
        /// </summary>
        public static string HTG {
            get {
                return ResourceManager.GetString("HTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUF.
        /// </summary>
        public static string HUF {
            get {
                return ResourceManager.GetString("HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR.
        /// </summary>
        public static string IDR {
            get {
                return ResourceManager.GetString("IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEP.
        /// </summary>
        public static string IEP {
            get {
                return ResourceManager.GetString("IEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILS.
        /// </summary>
        public static string ILS {
            get {
                return ResourceManager.GetString("ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INR.
        /// </summary>
        public static string INR {
            get {
                return ResourceManager.GetString("INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQD.
        /// </summary>
        public static string IQD {
            get {
                return ResourceManager.GetString("IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRR.
        /// </summary>
        public static string IRR {
            get {
                return ResourceManager.GetString("IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISK.
        /// </summary>
        public static string ISK {
            get {
                return ResourceManager.GetString("ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITL.
        /// </summary>
        public static string ITL {
            get {
                return ResourceManager.GetString("ITL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMD.
        /// </summary>
        public static string JMD {
            get {
                return ResourceManager.GetString("JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOD.
        /// </summary>
        public static string JOD {
            get {
                return ResourceManager.GetString("JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPY.
        /// </summary>
        public static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KES.
        /// </summary>
        public static string KES {
            get {
                return ResourceManager.GetString("KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KGS.
        /// </summary>
        public static string KGS {
            get {
                return ResourceManager.GetString("KGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHR.
        /// </summary>
        public static string KHR {
            get {
                return ResourceManager.GetString("KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHR.
        /// </summary>
        public static string KHR1 {
            get {
                return ResourceManager.GetString("KHR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMF.
        /// </summary>
        public static string KMF {
            get {
                return ResourceManager.GetString("KMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPW.
        /// </summary>
        public static string KPW {
            get {
                return ResourceManager.GetString("KPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRW.
        /// </summary>
        public static string KRW {
            get {
                return ResourceManager.GetString("KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWD.
        /// </summary>
        public static string KWD {
            get {
                return ResourceManager.GetString("KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYD.
        /// </summary>
        public static string KYD {
            get {
                return ResourceManager.GetString("KYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KZT.
        /// </summary>
        public static string KZT {
            get {
                return ResourceManager.GetString("KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAK.
        /// </summary>
        public static string LAK {
            get {
                return ResourceManager.GetString("LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LBP.
        /// </summary>
        public static string LBP {
            get {
                return ResourceManager.GetString("LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LKR.
        /// </summary>
        public static string LKR {
            get {
                return ResourceManager.GetString("LKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRD.
        /// </summary>
        public static string LRD {
            get {
                return ResourceManager.GetString("LRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSL.
        /// </summary>
        public static string LSL {
            get {
                return ResourceManager.GetString("LSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTL.
        /// </summary>
        public static string LTL {
            get {
                return ResourceManager.GetString("LTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUF.
        /// </summary>
        public static string LUF {
            get {
                return ResourceManager.GetString("LUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVL.
        /// </summary>
        public static string LVL {
            get {
                return ResourceManager.GetString("LVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LYD.
        /// </summary>
        public static string LYD {
            get {
                return ResourceManager.GetString("LYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAD.
        /// </summary>
        public static string MAD {
            get {
                return ResourceManager.GetString("MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDL.
        /// </summary>
        public static string MDL {
            get {
                return ResourceManager.GetString("MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGA.
        /// </summary>
        public static string MGA {
            get {
                return ResourceManager.GetString("MGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGF.
        /// </summary>
        public static string MGF {
            get {
                return ResourceManager.GetString("MGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKD.
        /// </summary>
        public static string MKD {
            get {
                return ResourceManager.GetString("MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMK.
        /// </summary>
        public static string MMK {
            get {
                return ResourceManager.GetString("MMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNT.
        /// </summary>
        public static string MNT {
            get {
                return ResourceManager.GetString("MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOP.
        /// </summary>
        public static string MOP {
            get {
                return ResourceManager.GetString("MOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRO.
        /// </summary>
        public static string MRO {
            get {
                return ResourceManager.GetString("MRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTL.
        /// </summary>
        public static string MTL {
            get {
                return ResourceManager.GetString("MTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUR.
        /// </summary>
        public static string MUR {
            get {
                return ResourceManager.GetString("MUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVR.
        /// </summary>
        public static string MVR {
            get {
                return ResourceManager.GetString("MVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWK.
        /// </summary>
        public static string MWK {
            get {
                return ResourceManager.GetString("MWK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MXN.
        /// </summary>
        public static string MXN {
            get {
                return ResourceManager.GetString("MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYR.
        /// </summary>
        public static string MYR {
            get {
                return ResourceManager.GetString("MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZM.
        /// </summary>
        public static string MZM {
            get {
                return ResourceManager.GetString("MZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZN.
        /// </summary>
        public static string MZN {
            get {
                return ResourceManager.GetString("MZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAD.
        /// </summary>
        public static string NAD {
            get {
                return ResourceManager.GetString("NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGN.
        /// </summary>
        public static string NGN {
            get {
                return ResourceManager.GetString("NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIO.
        /// </summary>
        public static string NIO {
            get {
                return ResourceManager.GetString("NIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLG.
        /// </summary>
        public static string NLG {
            get {
                return ResourceManager.GetString("NLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLG.
        /// </summary>
        public static string NLG1 {
            get {
                return ResourceManager.GetString("NLG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOK.
        /// </summary>
        public static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPR.
        /// </summary>
        public static string NPR {
            get {
                return ResourceManager.GetString("NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZD.
        /// </summary>
        public static string NZD {
            get {
                return ResourceManager.GetString("NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMR.
        /// </summary>
        public static string OMR {
            get {
                return ResourceManager.GetString("OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAB.
        /// </summary>
        public static string PAB {
            get {
                return ResourceManager.GetString("PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN.
        /// </summary>
        public static string PEN {
            get {
                return ResourceManager.GetString("PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGK.
        /// </summary>
        public static string PGK {
            get {
                return ResourceManager.GetString("PGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP.
        /// </summary>
        public static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKR.
        /// </summary>
        public static string PKR {
            get {
                return ResourceManager.GetString("PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLN.
        /// </summary>
        public static string PLN {
            get {
                return ResourceManager.GetString("PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTE.
        /// </summary>
        public static string PTE {
            get {
                return ResourceManager.GetString("PTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PYG.
        /// </summary>
        public static string PYG {
            get {
                return ResourceManager.GetString("PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAR.
        /// </summary>
        public static string QAR {
            get {
                return ResourceManager.GetString("QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROL.
        /// </summary>
        public static string ROL {
            get {
                return ResourceManager.GetString("ROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RON.
        /// </summary>
        public static string RON {
            get {
                return ResourceManager.GetString("RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSD.
        /// </summary>
        public static string RSD {
            get {
                return ResourceManager.GetString("RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUB.
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWF.
        /// </summary>
        public static string RWF {
            get {
                return ResourceManager.GetString("RWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBD.
        /// </summary>
        public static string SBD {
            get {
                return ResourceManager.GetString("SBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR.
        /// </summary>
        public static string SCR {
            get {
                return ResourceManager.GetString("SCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDD.
        /// </summary>
        public static string SDD {
            get {
                return ResourceManager.GetString("SDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDG.
        /// </summary>
        public static string SDG {
            get {
                return ResourceManager.GetString("SDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDP.
        /// </summary>
        public static string SDP {
            get {
                return ResourceManager.GetString("SDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEK.
        /// </summary>
        public static string SEK {
            get {
                return ResourceManager.GetString("SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGD.
        /// </summary>
        public static string SGD {
            get {
                return ResourceManager.GetString("SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHP.
        /// </summary>
        public static string SHP {
            get {
                return ResourceManager.GetString("SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIT.
        /// </summary>
        public static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKK.
        /// </summary>
        public static string SKK {
            get {
                return ResourceManager.GetString("SKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLL.
        /// </summary>
        public static string SLL {
            get {
                return ResourceManager.GetString("SLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        public static string SOS {
            get {
                return ResourceManager.GetString("SOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRD.
        /// </summary>
        public static string SRD {
            get {
                return ResourceManager.GetString("SRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRG.
        /// </summary>
        public static string SRG {
            get {
                return ResourceManager.GetString("SRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD.
        /// </summary>
        public static string STD {
            get {
                return ResourceManager.GetString("STD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVC.
        /// </summary>
        public static string SVC {
            get {
                return ResourceManager.GetString("SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYP.
        /// </summary>
        public static string SYP {
            get {
                return ResourceManager.GetString("SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZL.
        /// </summary>
        public static string SZL {
            get {
                return ResourceManager.GetString("SZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THB.
        /// </summary>
        public static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TJS.
        /// </summary>
        public static string TJS {
            get {
                return ResourceManager.GetString("TJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMM.
        /// </summary>
        public static string TMM {
            get {
                return ResourceManager.GetString("TMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMT.
        /// </summary>
        public static string TMT {
            get {
                return ResourceManager.GetString("TMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TND.
        /// </summary>
        public static string TND {
            get {
                return ResourceManager.GetString("TND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP.
        /// </summary>
        public static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRL.
        /// </summary>
        public static string TRL {
            get {
                return ResourceManager.GetString("TRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY.
        /// </summary>
        public static string TRY {
            get {
                return ResourceManager.GetString("TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTD.
        /// </summary>
        public static string TTD {
            get {
                return ResourceManager.GetString("TTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWD.
        /// </summary>
        public static string TWD {
            get {
                return ResourceManager.GetString("TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TZS.
        /// </summary>
        public static string TZS {
            get {
                return ResourceManager.GetString("TZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH.
        /// </summary>
        public static string UAH {
            get {
                return ResourceManager.GetString("UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH.
        /// </summary>
        public static string UAH1 {
            get {
                return ResourceManager.GetString("UAH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGX.
        /// </summary>
        public static string UGX {
            get {
                return ResourceManager.GetString("UGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYU.
        /// </summary>
        public static string UYU {
            get {
                return ResourceManager.GetString("UYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZS.
        /// </summary>
        public static string UZS {
            get {
                return ResourceManager.GetString("UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEB.
        /// </summary>
        public static string VEB {
            get {
                return ResourceManager.GetString("VEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEF.
        /// </summary>
        public static string VEF {
            get {
                return ResourceManager.GetString("VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        public static string VND {
            get {
                return ResourceManager.GetString("VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUV.
        /// </summary>
        public static string VUV {
            get {
                return ResourceManager.GetString("VUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WST.
        /// </summary>
        public static string WST {
            get {
                return ResourceManager.GetString("WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAF.
        /// </summary>
        public static string XAF {
            get {
                return ResourceManager.GetString("XAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAG.
        /// </summary>
        public static string XAG {
            get {
                return ResourceManager.GetString("XAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAU.
        /// </summary>
        public static string XAU {
            get {
                return ResourceManager.GetString("XAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCD.
        /// </summary>
        public static string XCD {
            get {
                return ResourceManager.GetString("XCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XEU.
        /// </summary>
        public static string XEU {
            get {
                return ResourceManager.GetString("XEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOF.
        /// </summary>
        public static string XOF {
            get {
                return ResourceManager.GetString("XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPD.
        /// </summary>
        public static string XPD {
            get {
                return ResourceManager.GetString("XPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPF.
        /// </summary>
        public static string XPF {
            get {
                return ResourceManager.GetString("XPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPT.
        /// </summary>
        public static string XPT {
            get {
                return ResourceManager.GetString("XPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YER.
        /// </summary>
        public static string YER {
            get {
                return ResourceManager.GetString("YER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YUN.
        /// </summary>
        public static string YUN {
            get {
                return ResourceManager.GetString("YUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAR.
        /// </summary>
        public static string ZAR {
            get {
                return ResourceManager.GetString("ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMK.
        /// </summary>
        public static string ZMK {
            get {
                return ResourceManager.GetString("ZMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMW.
        /// </summary>
        public static string ZMW {
            get {
                return ResourceManager.GetString("ZMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZWD.
        /// </summary>
        public static string ZWD {
            get {
                return ResourceManager.GetString("ZWD", resourceCulture);
            }
        }
    }
}
