//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdionFA.Infrastructure.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdionFA.Infrastructure.I18n.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembled builder completed.
        /// </summary>
        public static string AssembledBuilderCompleted {
            get {
                return ResourceManager.GetString("AssembledBuilderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation run with no results.
        /// </summary>
        public static string CorrelationRunWithNoResults {
            get {
                return ResourceManager.GetString("CorrelationRunWithNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol and timeframe must be the same for selected historical data and settings.
        /// </summary>
        public static string CurrencyPairAndCurrencyPeriodMustBeSame {
            get {
                return ResourceManager.GetString("CurrencyPairAndCurrencyPeriodMustBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed.
        /// </summary>
        public static string EntityErrorTransaction {
            get {
                return ResourceManager.GetString("EntityErrorTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved.
        /// </summary>
        public static string EntitySaveSuccess {
            get {
                return ResourceManager.GetString("EntitySaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction completed.
        /// </summary>
        public static string ExtractionCompleted {
            get {
                return ResourceManager.GetString("ExtractionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical data dile is empty.
        /// </summary>
        public static string MarketDataFileEmpty {
            get {
                return ResourceManager.GetString("MarketDataFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeframe cannot be null.
        /// </summary>
        public static string MarketDataPeriodCannotBeNull {
            get {
                return ResourceManager.GetString("MarketDataPeriodCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the symbol and timeframe from settings.
        /// </summary>
        public static string SetCurrencyPairAndPeriodFromConfiguration {
            get {
                return ResourceManager.GetString("SetCurrencyPairAndPeriodFromConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set data history from settings.
        /// </summary>
        public static string SetDataHistoryFromConfiguration {
            get {
                return ResourceManager.GetString("SetDataHistoryFromConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a valid date range from settings.
        /// </summary>
        public static string SetValidDateRangeFromConfiguration {
            get {
                return ResourceManager.GetString("SetValidDateRangeFromConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a valid directory from settings.
        /// </summary>
        public static string SetValidDirectoryFromConfiguration {
            get {
                return ResourceManager.GetString("SetValidDirectoryFromConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy builder completed.
        /// </summary>
        public static string StrategyBuilderCompleted {
            get {
                return ResourceManager.GetString("StrategyBuilderCompleted", resourceCulture);
            }
        }
    }
}
