//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdionFA.UI.Module.Shell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShellResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShellResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdionFA.UI.Module.Shell.Resources.ShellResources", typeof(ShellResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Data.
        /// </summary>
        public static string HistoricalData {
            get {
                return ResourceManager.GetString("HistoricalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Import.
        /// </summary>
        public static string OpenOrImport {
            get {
                return ResourceManager.GetString("OpenOrImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent.
        /// </summary>
        public static string OpenRecent {
            get {
                return ResourceManager.GetString("OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Off.
        /// </summary>
        public static string PinOff {
            get {
                return ResourceManager.GetString("PinOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin On.
        /// </summary>
        public static string PinOn {
            get {
                return ResourceManager.GetString("PinOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Global Configuration.
        /// </summary>
        public static string ProjectGlobalConfig {
            get {
                return ResourceManager.GetString("ProjectGlobalConfig", resourceCulture);
            }
        }
    }
}
