// <auto-generated />
using System;
using AdionFA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdionFA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdionFADbContext))]
    [Migration("20230716155449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("AdionFA.Domain.Entities.Configuration", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ABMinImprovePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("ABTransactionsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ABWekaMaxRatioTree")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ABWekaNTotalTree")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepthWeka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpertAdvisorHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpertAdvisorPublisherPort")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpertAdvisorResponsePort")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractorMinVariation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FromDateIS")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FromDateOS")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProgressiveness")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxProgressivenessVariation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxRatioTree")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumSeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimalSeed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NTotalTree")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMaxCorrelationPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMaxSuccessRateVariation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMinSuccessRatePercentIS")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMinSuccessRatePercentOS")
                        .HasColumnType("TEXT");

                    b.Property<int>("SBMinTransactionsIS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBMinTransactionsOS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBTransactionsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBWinningStrategyDOWNTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBWinningStrategyUPTarget")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeframeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ToDateIS")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ToDateOS")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDecimalWeka")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalInstanceWeka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WithoutSchedule")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TimeframeId");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            ConfigurationId = 1,
                            ABMinImprovePercent = 5m,
                            ABTransactionsTarget = 600,
                            ABWekaMaxRatioTree = 2m,
                            ABWekaNTotalTree = 500m,
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7292),
                            DepthWeka = 6,
                            Description = "Default Configuration",
                            ExtractorMinVariation = 50,
                            IsDeleted = false,
                            IsProgressiveness = false,
                            MaxProgressivenessVariation = 2m,
                            MaxRatioTree = 1.5m,
                            MaximumSeed = 1000000,
                            MinimalSeed = 100,
                            NTotalTree = 300m,
                            SBMaxCorrelationPercent = 2m,
                            SBMaxSuccessRateVariation = 4m,
                            SBMinSuccessRatePercentIS = 55m,
                            SBMinSuccessRatePercentOS = 55m,
                            SBMinTransactionsIS = 300,
                            SBMinTransactionsOS = 100,
                            SBTransactionsTarget = 300,
                            SBWinningStrategyDOWNTarget = 6,
                            SBWinningStrategyUPTarget = 6,
                            StartDate = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7290),
                            SymbolId = 1,
                            TimeframeId = 5,
                            TotalDecimalWeka = 5,
                            TotalInstanceWeka = 1,
                            WithoutSchedule = true
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.HistoricalData", b =>
                {
                    b.Property<int>("HistoricalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeframeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("HistoricalDataId");

                    b.HasIndex("MarketId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TimeframeId");

                    b.ToTable("HistoricalData");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.HistoricalDataCandle", b =>
                {
                    b.Property<int>("HistoricalDataCandleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Close")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<int>("HistoricalDataId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<double>("Spread")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("HistoricalDataCandleId");

                    b.HasIndex("HistoricalDataId");

                    b.ToTable("HistoricalDataCandle");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Market", b =>
                {
                    b.Property<int>("MarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("MarketId");

                    b.ToTable("Market");

                    b.HasData(
                        new
                        {
                            MarketId = 1,
                            Code = "Forex",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6912),
                            Description = "",
                            IsDeleted = false,
                            Name = "Forex"
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.MarketRegion", b =>
                {
                    b.Property<int>("MarketRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("MarketRegionId");

                    b.ToTable("MarketRegion");

                    b.HasData(
                        new
                        {
                            MarketRegionId = 1,
                            Code = "America",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7065),
                            Description = "",
                            IsDeleted = false,
                            Name = "America"
                        },
                        new
                        {
                            MarketRegionId = 2,
                            Code = "Europe",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7165),
                            Description = "",
                            IsDeleted = false,
                            Name = "Europe"
                        },
                        new
                        {
                            MarketRegionId = 3,
                            Code = "Asia",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7255),
                            Description = "",
                            IsDeleted = false,
                            Name = "Asia"
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectName")
                        .IsUnique();

                    b.ToTable("Project");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ProjectConfiguration", b =>
                {
                    b.Property<int>("ProjectConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ABMinImprovePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("ABTransactionsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ABWekaMaxRatioTree")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ABWekaNTotalTree")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepthWeka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpertAdvisorHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpertAdvisorPublisherPort")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpertAdvisorResponsePort")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractorMinVariation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FromDateIS")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FromDateOS")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HistoricalDataId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProgressiveness")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxProgressivenessVariation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxRatioTree")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumSeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimalSeed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NTotalTree")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SBMaxCorrelationPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMaxSuccessRateVariation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMinSuccessRatePercentIS")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SBMinSuccessRatePercentOS")
                        .HasColumnType("TEXT");

                    b.Property<int>("SBMinTransactionsIS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBMinTransactionsOS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBTransactionsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBWinningStrategyDOWNTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SBWinningStrategyUPTarget")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeframeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ToDateIS")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ToDateOS")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDecimalWeka")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalInstanceWeka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WithoutSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectConfigurationId");

                    b.HasIndex("HistoricalDataId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TimeframeId");

                    b.ToTable("ProjectConfiguration");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ProjectScheduleConfiguration", b =>
                {
                    b.Property<int>("ProjectScheduleConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MarketRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectScheduleConfigurationId");

                    b.HasIndex("MarketRegionId");

                    b.HasIndex("ProjectConfigurationId");

                    b.ToTable("ProjectScheduleConfiguration");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ScheduleConfiguration", b =>
                {
                    b.Property<int>("ScheduleConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MarketRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("MarketRegionId");

                    b.ToTable("ScheduleConfiguration");

                    b.HasData(
                        new
                        {
                            ScheduleConfigurationId = 1,
                            ConfigurationId = 1,
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7312),
                            Description = "Default Schedule America",
                            FromTimeInSeconds = 54000,
                            IsDeleted = false,
                            MarketRegionId = 1,
                            StartDate = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7311),
                            ToTimeInSeconds = 82800
                        },
                        new
                        {
                            ScheduleConfigurationId = 2,
                            ConfigurationId = 1,
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7315),
                            Description = "Default Schedule Europe",
                            FromTimeInSeconds = 32400,
                            IsDeleted = false,
                            MarketRegionId = 2,
                            StartDate = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7313),
                            ToTimeInSeconds = 64800
                        },
                        new
                        {
                            ScheduleConfigurationId = 3,
                            ConfigurationId = 1,
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7354),
                            Description = "Default Schedule Asia",
                            FromTimeInSeconds = 3600,
                            IsDeleted = false,
                            MarketRegionId = 3,
                            StartDate = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(7352),
                            ToTimeInSeconds = 32400
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("Setting");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            Code = "Culture",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5076),
                            IsDeleted = false,
                            Value = "eng"
                        },
                        new
                        {
                            SettingId = 2,
                            Code = "Theme",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5212),
                            IsDeleted = false,
                            Value = "Light"
                        },
                        new
                        {
                            SettingId = 3,
                            Code = "Color",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5383),
                            IsDeleted = false,
                            Value = "Orange"
                        },
                        new
                        {
                            SettingId = 4,
                            Code = "DefaultWorkspace",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5503),
                            IsDeleted = false,
                            Value = ""
                        },
                        new
                        {
                            SettingId = 5,
                            Code = "Host",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5607),
                            IsDeleted = false,
                            Value = "192.168.50.137"
                        },
                        new
                        {
                            SettingId = 6,
                            Code = "Port",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5709),
                            IsDeleted = false,
                            Value = "5555"
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Symbol", b =>
                {
                    b.Property<int>("SymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("SymbolId");

                    b.ToTable("Symbol");

                    b.HasData(
                        new
                        {
                            SymbolId = 1,
                            Code = "EURUSD",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5731),
                            Description = "Euro vs US Dollar",
                            IsDeleted = false,
                            Name = "EURUSD"
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Timeframe", b =>
                {
                    b.Property<int>("TimeframeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeframeId");

                    b.ToTable("Timeframe");

                    b.HasData(
                        new
                        {
                            TimeframeId = 1,
                            Code = "M1",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(5916),
                            Description = "",
                            IsDeleted = false,
                            Name = "M1",
                            Value = "1"
                        },
                        new
                        {
                            TimeframeId = 2,
                            Code = "M5",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6055),
                            Description = "",
                            IsDeleted = false,
                            Name = "M5",
                            Value = "5"
                        },
                        new
                        {
                            TimeframeId = 3,
                            Code = "M15",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6156),
                            Description = "",
                            IsDeleted = false,
                            Name = "M15",
                            Value = "15"
                        },
                        new
                        {
                            TimeframeId = 4,
                            Code = "M30",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6254),
                            Description = "",
                            IsDeleted = false,
                            Name = "M30",
                            Value = "30"
                        },
                        new
                        {
                            TimeframeId = 5,
                            Code = "H1",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6348),
                            Description = "",
                            IsDeleted = false,
                            Name = "H1",
                            Value = "16385"
                        },
                        new
                        {
                            TimeframeId = 6,
                            Code = "H4",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6446),
                            Description = "",
                            IsDeleted = false,
                            Name = "H4",
                            Value = "16388"
                        },
                        new
                        {
                            TimeframeId = 7,
                            Code = "D1",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6537),
                            Description = "",
                            IsDeleted = false,
                            Name = "D1",
                            Value = "16408"
                        },
                        new
                        {
                            TimeframeId = 8,
                            Code = "W1",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6629),
                            Description = "",
                            IsDeleted = false,
                            Name = "W1",
                            Value = "32769"
                        },
                        new
                        {
                            TimeframeId = 9,
                            Code = "MN1",
                            CreatedById = "0",
                            CreatedByUserName = "admin",
                            CreatedOn = new DateTime(2023, 7, 16, 15, 54, 49, 451, DateTimeKind.Utc).AddTicks(6770),
                            Description = "",
                            IsDeleted = false,
                            Name = "MN1",
                            Value = "49153"
                        });
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Configuration", b =>
                {
                    b.HasOne("AdionFA.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdionFA.Domain.Entities.Timeframe", "Timeframe")
                        .WithMany()
                        .HasForeignKey("TimeframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("Timeframe");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.HistoricalData", b =>
                {
                    b.HasOne("AdionFA.Domain.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdionFA.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdionFA.Domain.Entities.Timeframe", "Timeframe")
                        .WithMany()
                        .HasForeignKey("TimeframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Symbol");

                    b.Navigation("Timeframe");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.HistoricalDataCandle", b =>
                {
                    b.HasOne("AdionFA.Domain.Entities.HistoricalData", "HistoricalData")
                        .WithMany("HistoricalDataCandles")
                        .HasForeignKey("HistoricalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalData");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ProjectConfiguration", b =>
                {
                    b.HasOne("AdionFA.Domain.Entities.HistoricalData", "HistoricalData")
                        .WithMany()
                        .HasForeignKey("HistoricalDataId");

                    b.HasOne("AdionFA.Domain.Entities.Project", "Project")
                        .WithMany("ProjectConfigurations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdionFA.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdionFA.Domain.Entities.Timeframe", "Timeframe")
                        .WithMany()
                        .HasForeignKey("TimeframeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalData");

                    b.Navigation("Project");

                    b.Navigation("Symbol");

                    b.Navigation("Timeframe");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ProjectScheduleConfiguration", b =>
                {
                    b.HasOne("AdionFA.Domain.Entities.MarketRegion", "MarketRegion")
                        .WithMany()
                        .HasForeignKey("MarketRegionId");

                    b.HasOne("AdionFA.Domain.Entities.ProjectConfiguration", "ProjectConfiguration")
                        .WithMany("ProjectScheduleConfigurations")
                        .HasForeignKey("ProjectConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketRegion");

                    b.Navigation("ProjectConfiguration");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ScheduleConfiguration", b =>
                {
                    b.HasOne("AdionFA.Domain.Entities.Configuration", "Configuration")
                        .WithMany("ScheduleConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdionFA.Domain.Entities.MarketRegion", "MarketRegion")
                        .WithMany()
                        .HasForeignKey("MarketRegionId");

                    b.Navigation("Configuration");

                    b.Navigation("MarketRegion");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Configuration", b =>
                {
                    b.Navigation("ScheduleConfigurations");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.HistoricalData", b =>
                {
                    b.Navigation("HistoricalDataCandles");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectConfigurations");
                });

            modelBuilder.Entity("AdionFA.Domain.Entities.ProjectConfiguration", b =>
                {
                    b.Navigation("ProjectScheduleConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
